#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/application
- name: Run app
  docker_container:
    name: my-api
    image: lionyti/tp-devops-simple-api
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3